- name: Pull and create Calculator Docker container
  hosts: local
  gather_facts: false

  tasks:
    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started

    - name: Pull Docker image
      community.docker.docker_image:
          name: madhavgirdhar/calculator:latest
          source: pull

    - name: Remove existing container if present
      community.docker.docker_container:
          name: calculator
          state: absent

    - name: Create Calculator container (do not start)
      ansible.builtin.command: docker create -it --name calculator madhavgirdhar/calculator:latest